### ISSUE TITLE
2018: Relação dos grupos

### ISSUE THREAD

**Issue by jemaf** [COLTEC-DAW/TP-RESTFul-App#5]

**Comment by jemaf** [comment]
Para cada dupla, definir:

* Nome dos integrantes
* API que será utilizada no trabalho

**Comment by gegen07** [comment]
- Bryan e Germano
- https://github.com/r-spacex/SpaceX-API

**Comment by oliveira-mathias** [comment]
- Mathias e Dener
- GIPHY API
